#include <stdio.h>

#include "errnoi_data.h"

errnoi_t errnoi_data[] = {
errnoi_data_f(EPERM     ,    1   ,  Operation not permitted ),
errnoi_data_f(ENOENT    ,     2  ,   No such file or directory ),
errnoi_data_f(ESRCH     ,    3   ,  No such process ),
errnoi_data_f(EINTR     ,    4   ,  Interrupted system call ),
errnoi_data_f(EIO       ,      5 ,    I/O error ),
errnoi_data_f(ENXIO     ,    6   ,  No such device or address ),
errnoi_data_f(E2BIG     ,    7   ,  Argument list too long ),
errnoi_data_f(ENOEXEC   ,      8 ,    Exec format error ),
errnoi_data_f(EBADF     ,    9   ,  Bad file number ),
errnoi_data_f(ECHILD    ,    10  ,   No child processes ),
errnoi_data_f(EAGAIN    ,    11  ,   Try again ),
errnoi_data_f(ENOMEM    ,    12  ,   Out of memory ),
errnoi_data_f(EACCES    ,    13  ,   Permission denied ),
errnoi_data_f(EFAULT    ,    14  ,   Bad address ),
errnoi_data_f(ENOTBLK   ,     15 ,    Block device required ),
errnoi_data_f(EBUSY     ,   16   ,  Device or resource busy ),
errnoi_data_f(EEXIST    ,    17  ,   File exists ),
errnoi_data_f(EXDEV     ,   18   ,  Cross-device link ),
errnoi_data_f(ENODEV    ,    19  ,   No such device ),
errnoi_data_f(ENOTDIR   ,     20 ,    Not a directory ),
errnoi_data_f(EISDIR    ,    21  ,   Is a directory ),
errnoi_data_f(EINVAL    ,    22  ,   Invalid argument ),
errnoi_data_f(ENFILE    ,    23  ,   File table overflow ),
errnoi_data_f(EMFILE    ,    24  ,   Too many open files ),
errnoi_data_f(ENOTTY    ,    25  ,   Not a typewriter ),
errnoi_data_f(ETXTBSY   ,     26 ,    Text file busy ),
errnoi_data_f(EFBIG     ,   27   ,  File too large ),
errnoi_data_f(ENOSPC    ,    28  ,   No space left on device ),
errnoi_data_f(ESPIPE    ,    29  ,   Illegal seek ),
errnoi_data_f(EROFS     ,   30   ,  Read-only file system ),
errnoi_data_f(EMLINK    ,    31  ,   Too many links ),
errnoi_data_f(EPIPE     ,   32   ,  Broken pipe ),
errnoi_data_f(EDOM      ,  33    , Math argument out of domain of func ),
errnoi_data_f(ERANGE    ,    34  ,   Math result not representable ),
errnoi_data_f(EDEADLK   ,     35 ,    Resource deadlock would occur ),
errnoi_data_f(ENAMETOOLONG ,   36 ,    File name too long ),
errnoi_data_f(ENOLCK     ,   37  ,   No record locks available ),
errnoi_data_f(ENOSYS     ,   38  ,   Invalid system call number ),
errnoi_data_f(ENOTEMPTY  ,  39   ,  Directory not empty ),
errnoi_data_f(ELOOP      ,  40   ,  Too many symbolic links encountered ),
errnoi_data_f(EWOULDBLOCK,    11   ,  Operation would block ),
errnoi_data_f(ENOMSG     ,   42   ,  No message of desired type ),
errnoi_data_f(EIDRM      ,  43    , Identifier removed ),
errnoi_data_f(ECHRNG     ,   44   ,  Channel number out of range ),
errnoi_data_f(EL2NSYNC   , 45     ,Level 2 not synchronized ),
errnoi_data_f(EL3HLT     ,   46   ,  Level 3 halted ),
errnoi_data_f(EL3RST     ,   47   ,  Level 3 reset ),
errnoi_data_f(ELNRNG     ,   48   ,  Link number out of range ),
errnoi_data_f(EUNATCH    ,    49  ,   Protocol driver not attached ),
errnoi_data_f(ENOCSI     ,   50   ,  No CSI structure available ),
errnoi_data_f(EL2HLT     ,   51   ,  Level 2 halted ),
errnoi_data_f(EBADE      ,  52    , Invalid exchange ),
errnoi_data_f(EBADR      ,  53    , Invalid request descriptor ),
errnoi_data_f(EXFULL     ,   54   ,  Exchange full ),
errnoi_data_f(ENOANO     ,   55   ,  No anode ),
errnoi_data_f(EBADRQC    ,    56  ,   Invalid request code ),
errnoi_data_f(EBADSLT    ,    57  ,   Invalid slot ),
errnoi_data_f(EDEADLOCK  ,  35, Resource deadlock would occur ),
errnoi_data_f(EBFONT     ,   59  ,   Bad font file format ),
errnoi_data_f(ENOSTR     ,   60  ,   Device not a stream ),
errnoi_data_f(ENODATA    ,    61 ,    No data available ),
errnoi_data_f(ETIME      ,  62   ,  Timer expired ),
errnoi_data_f(ENOSR      ,  63   ,  Out of streams resources ),
errnoi_data_f(ENONET     ,   64  ,   Machine is not on the network ),
errnoi_data_f(ENOPKG     ,   65  ,   Package not installed ),
errnoi_data_f(EREMOTE    ,    66 ,    Object is remote ),
errnoi_data_f(ENOLINK    ,    67 ,    Link has been severed ),
errnoi_data_f(EADV       , 68    , Advertise error ),
errnoi_data_f(ESRMNT     ,   69  ,   Srmount error ),
errnoi_data_f(ECOMM      ,  70   ,  Communication error on send ),
errnoi_data_f(EPROTO     ,   71  ,   Protocol error ),
errnoi_data_f(EMULTIHOP  ,  72   ,  Multihop attempted ),
errnoi_data_f(EDOTDOT    ,    73 ,    RFS specific error ),
errnoi_data_f(EBADMSG    ,    74 ,    Not a data message ),
errnoi_data_f(EOVERFLOW  ,  75   ,  Value too large for defined data type ),
errnoi_data_f(ENOTUNIQ   , 76    , Name not unique on network ),
errnoi_data_f(EBADFD     ,   77  ,   File descriptor in bad state ),
errnoi_data_f(EREMCHG    ,    78 ,    Remote address changed ),
errnoi_data_f(ELIBACC    ,    79 ,    Can not access a needed shared library ),
errnoi_data_f(ELIBBAD    ,    80 ,    Accessing a corrupted shared library ),
errnoi_data_f(ELIBSCN    ,    81 ,    .lib section in a.out corrupted ),
errnoi_data_f(ELIBMAX    ,    82 ,    Attempting to link in too many shared libraries ),
errnoi_data_f(ELIBEXEC   , 83    , Cannot exec a shared library directly ),
errnoi_data_f(EILSEQ     ,   84  ,   Illegal byte sequence ),
errnoi_data_f(ERESTART   , 85    , Interrupted system call should be restarted ),
errnoi_data_f(ESTRPIPE   , 86    , Streams pipe error ),
errnoi_data_f(EUSERS     ,   87  ,   Too many users ),
errnoi_data_f(ENOTSOCK   , 88    , Socket operation on non-socket ),
errnoi_data_f(EDESTADDRREQ   , 89 ,    Destination address required ),
errnoi_data_f(EMSGSIZE    ,90    , Message too long ),
errnoi_data_f(EPROTOTYPE   , 91  ,   Protocol wrong type for socket ),
errnoi_data_f(ENOPROTOOPT  ,  92 ,    Protocol not available ),
errnoi_data_f(EPROTONOSUPPORT    ,93   ,  Protocol not supported ),
errnoi_data_f(ESOCKTNOSUPPORT   , 94   ,  Socket type not supported ),
errnoi_data_f(EOPNOTSUPP   , 95    , Operation not supported on transport endpoint ),
errnoi_data_f(EPFNOSUPPORT   , 96  ,   Protocol family not supported ),
errnoi_data_f(EAFNOSUPPORT  ,  97  ,   Address family not supported by protocol ),
errnoi_data_f(EADDRINUSE  ,  98    , Address already in use ),
errnoi_data_f(EADDRNOTAVAIL ,   99 ,    Cannot assign requested address ),
errnoi_data_f(ENETDOWN   , 100     ,Network is down ),
errnoi_data_f(ENETUNREACH  ,  101  ,   Network is unreachable ),
errnoi_data_f(ENETRESET   , 102    , Network dropped connection because of reset ),
errnoi_data_f(ECONNABORTED  ,  103 ,    Software caused connection abort ),
errnoi_data_f(ECONNRESET  ,  104   ,  Connection reset by peer ),
errnoi_data_f(ENOBUFS     ,   105  ,   No buffer space available ),
errnoi_data_f(EISCONN     ,   106  ,   Transport endpoint is already connected ),
errnoi_data_f(ENOTCONN    ,107     ,Transport endpoint is not connected ),
errnoi_data_f(ESHUTDOWN    ,108    , Cannot send after transport endpoint shutdown ),
errnoi_data_f(ETOOMANYREFS ,   109 ,    Too many references: cannot splice ),
errnoi_data_f(ETIMEDOUT    ,110    , Connection timed out ),
errnoi_data_f(ECONNREFUSED ,   111 ,    Connection refused ),
errnoi_data_f(EHOSTDOWN    ,112    , Host is down ),
errnoi_data_f(EHOSTUNREACH ,113 ,    No route to host ),
errnoi_data_f(EALREADY    ,114    , Operation already in progress ),
errnoi_data_f(EINPROGRESS ,   115 ,    Operation now in progress ),
errnoi_data_f(ESTALE      ,  116  ,   Stale file handle ),
errnoi_data_f(EUCLEAN     ,   117 ,    Structure needs cleaning ),
errnoi_data_f(ENOTNAM     ,   118 ,    Not a XENIX named type file ),
errnoi_data_f(ENAVAIL     ,   119 ,    No XENIX semaphores available ),
errnoi_data_f(EISNAM      ,  120  ,   Is a named type file ),
errnoi_data_f(EREMOTEIO   , 121   ,  Remote I/O error ),
errnoi_data_f(EDQUOT      ,  122  ,   Quota exceeded ),
errnoi_data_f(ENOMEDIUM   , 123   ,  No medium found ),
errnoi_data_f(EMEDIUMTYPE ,   124 ,    Wrong medium type ),
errnoi_data_f(ECANCELED   , 125   ,  Operation Canceled ),
errnoi_data_f(ENOKEY      ,  126  ,   Required key not available ),
errnoi_data_f(EKEYEXPIRED ,   127 ,    Key has expired ),
errnoi_data_f(EKEYREVOKED ,   128 ,    Key has been revoked ),
errnoi_data_f(EKEYREJECTED,    129,     Key was rejected by service ),
errnoi_data_f(EOWNERDEAD  ,  130  ,   Owner died ),
errnoi_data_f(ENOTRECOVERABLE    ,131,     State not recoverable ),
errnoi_data_f(ERFKILL       ,132    , Operation not possible due to RF-kill ),
errnoi_data_f(EHWPOISON    ,133    , Memory page has hardware error )
};

size_t errnoi_data_len = sizeof(errnoi_data) / sizeof(errnoi_t);
